/**
 * Custom Monaco editor dark theme for Postgrify's SQL editor.
 * Based on One Dark Pro palette.
 */
export const sqlTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "keyword", foreground: "C678DD", fontStyle: "bold" },
    { token: "keyword.sql", foreground: "C678DD", fontStyle: "bold" },
    { token: "string", foreground: "98C379" },
    { token: "string.sql", foreground: "98C379" },
    { token: "number", foreground: "D19A66" },
    { token: "number.sql", foreground: "D19A66" },
    { token: "comment", foreground: "5C6370", fontStyle: "italic" },
    { token: "comment.sql", foreground: "5C6370", fontStyle: "italic" },
    { token: "operator", foreground: "56B6C2" },
    { token: "operator.sql", foreground: "56B6C2" },
    { token: "identifier", foreground: "E06C75" },
    { token: "type", foreground: "E5C07B" },
    { token: "predefined", foreground: "61AFEF" },
  ],
  colors: {
    "editor.background": "#0F172A",
    "editor.foreground": "#CBD5E1",
    "editor.lineHighlightBackground": "#1E293B",
    "editor.selectionBackground": "#3B4D6B",
    "editor.inactiveSelectionBackground": "#2D3F57",
    "editorLineNumber.foreground": "#334155",
    "editorLineNumber.activeForeground": "#64748B",
    "editorCursor.foreground": "#60A5FA",
    "editorWhitespace.foreground": "#1E293B",
    "editorIndentGuide.background": "#1E293B",
    "editorIndentGuide.activeBackground": "#334155",
    "editor.findMatchBackground": "#854D0E50",
    "editor.findMatchHighlightBackground": "#854D0E30",
    "editorSuggestWidget.background": "#1E293B",
    "editorSuggestWidget.border": "#334155",
    "editorSuggestWidget.selectedBackground": "#2D4A7A",
    "editorHoverWidget.background": "#1E293B",
    "editorHoverWidget.border": "#334155",
    "scrollbarSlider.background": "#33415520",
    "scrollbarSlider.hoverBackground": "#33415540",
    "scrollbarSlider.activeBackground": "#33415560",
  },
};